name: Stop Dev Proxy
description: Stop Dev Proxy
runs:
  using: composite
  steps:
    - name: Stop Dev Proxy
      id: stop
      run: |
        curl -X POST http://127.0.0.1:8897/proxy/stopproxy
        echo "http_proxy=" >> $GITHUB_ENV
        echo "https_proxy=" >> $GITHUB_ENV
      shell: bash
