name: Install Dev Proxy
description: Install Dev Proxy with optional version specification
inputs:
  version:
    description: Version of Dev Proxy to install (e.g., v1.0.0). If not specified, the latest version will be installed.
    required: false
  called-by-setup:
    description: Indicates if this action is called by the setup action
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Deprecated
      if: ${{ inputs.called-by-setup == 'false' }}
      run: |
        echo "⚠️ This action is deprecated. Use 'dev-proxy-tools/actions/setup@v1' instead."
      shell: bash

    - name: Install Dev Proxy
      id: install
      run: |
        echo "🔧 Installing Dev Proxy..."

        # Check if version contains beta
        is_beta=false
        if [ -n "${{ inputs.version }}" ] && echo "${{ inputs.version }}" | grep -q "\-beta"; then
          is_beta=true
          echo "DEVPROXY_BETA=true" >> $GITHUB_ENV
        fi

        # Construct the installation command
        if [ -n "${{ inputs.version }}" ]; then
          if [ "$is_beta" = true ]; then
            echo "📋 Installing Dev Proxy beta version: ${{ inputs.version }}"
            bash -c "$(curl -sL https://aka.ms/devproxy/setup-beta.sh)" -- "${{ inputs.version }}"
          else
            echo "📋 Installing Dev Proxy version: ${{ inputs.version }}"
            bash -c "$(curl -sL https://aka.ms/devproxy/setup.sh)" -- "${{ inputs.version }}"
          fi
        else
          echo "📋 Installing latest version of Dev Proxy"
          bash -c "$(curl -sL https://aka.ms/devproxy/setup.sh)"
        fi

        echo "✅ Dev Proxy installed successfully!"
      shell: bash
