name: Start recording
description: Start recording
runs:
  using: composite
  steps:
    - name: Start recording
      id: stop
      run: |
        curl -X POST http://127.0.0.1:8897/proxy \
          -H "Content-Type: application/json" \
          -d '{"recording": true}'
      shell: bash