name: Start Dev Proxy
description: Start Dev Proxy
inputs:
  log-file:
    description: The file to log Dev Proxy output to
    required: true
    default: devproxy.log
  config-file:
    description: The path to the Dev Proxy configuration file
    required: false
  auto-record:
    description: Automatically start recording after starting Dev Proxy
    required: false
    default: "false"
  auto-stop:
    description: Automatically stop Dev Proxy when workflow completes
    required: false
    default: "true"
outputs:
  proxy-url:
    description: The URL of the running Dev Proxy instance
    value: ${{ steps.start-with-post-step.outputs.proxy-url }}
  api-url:
    description: The URL of the Dev Proxy API
    value: ${{ steps.start-with-post-step.outputs.api-url }}
runs:
  using: composite
  steps:
    - name: Start Dev Proxy with post step
      id: start-with-post-step
      uses: pyTooling/Actions/with-post-step@v5.1.0
      with:
        main: |
          # Make script executable
          chmod +x ${{ github.action_path }}/../scripts/start-devproxy.sh

          # Call the start script
          ${{ github.action_path }}/../scripts/start-devproxy.sh \
            "${{ inputs.log-file }}" "${{ inputs.config-file }}"
        post: |
          # Make script executable
          chmod +x ${{ github.action_path }}/../scripts/stop-devproxy.sh

          # Call the stop script
          ${{ github.action_path }}/../scripts/stop-devproxy.sh \
            "${{ inputs.auto-stop }}"

    - name: Start recording (conditional)
      if: ${{ inputs.auto-record == 'true' }}
      uses: ./record-start
