name: Start Dev Proxy
description: Start Dev Proxy
inputs:
  log-file:
    description: The file to log Dev Proxy output to
    required: true
    default: devproxy.log
  config-file:
    description: The path to the Dev Proxy configuration file
    required: false
  auto-stop:
    description: Automatically stop Dev Proxy when workflow completes
    required: false
    default: "true"
outputs:
  proxy-url:
    description: The URL of the running Dev Proxy instance
    value: ${{ steps.start-with-post-step.outputs.proxy-url }}
  api-url:
    description: The URL of the Dev Proxy API
    value: ${{ steps.start-with-post-step.outputs.api-url }}
runs:
  using: composite
  steps:
    - name: Start Dev Proxy with post step
      id: start-with-post-step
      uses: pyTooling/Actions/with-post-step@v5.1.0
      with:
        main: |
          log_file="${{ inputs.log-file }}"

          echo "Starting Dev Proxy..."

          # Create directory for Dev Proxy configuration and certificates
    
          root_cert_dir="$HOME/.config/dev-proxy"
          mkdir -p "$root_cert_dir"

          # Set certificate path
          cert_path="$root_cert_dir/rootCert.pfx"

          echo "Using certificate path: $cert_path"

          # Set environment variables for Dev Proxy
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
                   
          # Set config arguments if provided
          config_arg=""
          if [ -n "${{ inputs.config-file }}" ]; then
            config_arg="-c ${{ inputs.config-file }}"
          fi

          # Use appropriate executable based on whether beta version was installed
          devproxy_exec="./devproxy/devproxy"
          if [ "$DEVPROXY_BETA" = "true" ]; then
            devproxy_exec="./devproxy-beta/devproxy-beta"
          fi

          # start Dev Proxy in the background
          # log Dev Proxy output to the log file
          # log stdout and stderr to the file
          $devproxy_exec $config_arg > $log_file 2>&1 &

          # wait for init
          echo "Waiting for Dev Proxy to start..."
          while true; do
            if grep -q "Configure your operating system to use this proxy's port and address 127.0.0.1:8000" $log_file; then
              break
            fi
            sleep 1
          done

          echo "Dev Proxy is running!"
          
          # Set action outputs
          echo "proxy-url=http://127.0.0.1:8000" >> $GITHUB_OUTPUT
          echo "api-url=http://127.0.0.1:8897/proxy" >> $GITHUB_OUTPUT

          echo "🔒 Trusting Dev Proxy certificate..."

          echo "Checking for certificate at: $cert_path"
          if [ -f "$cert_path" ]; then
            echo "✅ Certificate found"
            
            echo "Exporting the Dev Proxy's Root Certificate"
            if openssl pkcs12 -in "$cert_path" -clcerts -nokeys -out dev-proxy-ca.crt -passin pass:""; then
              echo "Installing the Dev Proxy's Root Certificate"
              sudo cp dev-proxy-ca.crt /usr/local/share/ca-certificates/

              echo "Updating the CA certificates"
              sudo update-ca-certificates
              
              # Set the system proxy settings
              echo "http_proxy=http://127.0.0.1:8000" >> $GITHUB_ENV
              echo "https_proxy=http://127.0.0.1:8000" >> $GITHUB_ENV
                    
              echo "✅ Dev Proxy certificate trusted successfully!"
            else
              echo "❌ Failed to export certificate from $cert_path"
              echo "⚠️ SSL verification may fail"
            fi
          else
            echo "❌ Certificate not found at: $cert_path"
            echo "⚠️ Skipping certificate trust - SSL verification may fail"
          fi
        post: |
          if [ "${{ inputs.auto-stop }}" = "true" ]; then
            echo "Stopping Dev Proxy..."
            curl -X POST http://127.0.0.1:8897/proxy/stopproxy
            echo "http_proxy=" >> $GITHUB_ENV
            echo "https_proxy=" >> $GITHUB_ENV
            echo "Dev Proxy has been stopped."
          fi