name: Test Dev Proxy LLM Usage with Playwright

on:
  workflow_dispatch:

jobs:
  test-playwright-web-app:
    name: Test Dev Proxy LLM Usage with Playwright
    runs-on: ubuntu-latest
    permissions:
      models: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update env.js
        working-directory: ./samples/llm-usage
        run: |
          echo "Updating env.js..."
          echo "export const apiKey = '${{ secrets.GITHUB_TOKEN }}';" > ./js/env.js

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./samples/llm-usage
        run: npm ci

      - name: Install Edge browser
        working-directory: ./samples/llm-usage
        run: npm run install:msedge

      - name: Setup Dev Proxy
        uses: ./setup
        with:
          auto-record: true
          auto-stop: false
          config-file: ./samples/llm-usage/.devproxy/devproxyrc.json
          report-job-summary: $GITHUB_STEP_SUMMARY
          version: v1.0.0-beta.8

      - name: Install the Dev Proxy certificate for Chromium
        uses: ./chromium-cert

      - name: Run Playwright tests
        working-directory: ./samples/llm-usage
        run: DEBUG=pw:api npx playwright test

      - name: Stop recording
        if: always()
        uses: ./record-stop

      - name: Upload Dev Proxy reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: ./*Reporter*

      - name: Upload Dev Proxy logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devproxy.log
          path: devproxy.log

      - name: Show logs
        if: always()
        run: |
          echo "Dev Proxy logs:"
          cat devproxy.log