name: Test Dev Proxy Actions with defaults

on:
  workflow_dispatch:

jobs:
  test-dev-proxy-actions-defaults:
    name: Test Dev Proxy Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Intall Dev Proxy
        id: install-latest
        uses: ./install

      - name: Start Dev Proxy
        id: start-devproxy
        uses: ./start          

      - name: Start recording
        id: start-recording
        uses: ./record-start

      - name: Send request using output
        id: send-request
        run: |
          echo "Using proxy URL from output: ${{ steps.start-devproxy.outputs.proxy-url }}"
          curl -ikx "${{ steps.start-devproxy.outputs.proxy-url }}" https://jsonplaceholder.typicode.com/posts

      - name: Stop recording
        id: stop-recording
        uses: ./record-stop

      - name: Show logs
        run: |
          echo "Dev Proxy logs:"
          cat devproxy.log
