name: Test Start Action with Report Job Summary

on:
  workflow_dispatch:

jobs:
  test-start-report-job-summary:
    name: Test Start Action with Report Job Summary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dev Proxy
        id: install-latest
        uses: ./install

      - name: Start Dev Proxy with report-job-summary
        id: start-devproxy
        uses: ./start
        with:
          log-file: devproxy.log
          auto-record: "true"
          report-job-summary: $GITHUB_STEP_SUMMARY

      - name: Verify Dev Proxy is running
        run: |
          echo "🔍 Verifying Dev Proxy is running..."
          response=$(curl -s --max-time 10 \
            ${{ steps.start-devproxy.outputs.api-url }})
          if [ $? -eq 0 ] && [ -n "$response" ]; then
            echo "✅ Dev Proxy is running and responsive"
            echo "📋 API Response: $response"
          else
            echo "❌ Dev Proxy is not responsive"
            exit 1
          fi

      - name: Test Proxy with Recording
        run: |
          echo "🔍 Testing proxy functionality with recording..."
          curl -ikx "${{ steps.start-devproxy.outputs.proxy-url }}" \
            https://jsonplaceholder.typicode.com/posts

      - name: Stop recording
        uses: ./record-stop

      - name: Show logs
        if: always()
        run: |
          echo "📋 Dev Proxy logs:"
          if [ -f "devproxy.log" ]; then
            cat devproxy.log
          else
            echo "No log file found"
          fi

      - name: Check if reports were generated
        if: always()
        run: |
          echo "🔍 Checking if reports were generated..."
          ls -la ./*Reporter* || echo "No reports found"