name: Test Start Action - Old vs New Approach

on:
  workflow_dispatch:

jobs:
  test-old-approach:
    name: Test Old Approach (Manual Record Start)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dev Proxy
        id: install-latest
        uses: ./install

      - name: Start Dev Proxy
        id: start-devproxy
        uses: ./start
        with:
          log-file: devproxy.log

      - name: Start recording
        uses: ./record-start

      - name: Send request
        run: |
          curl -ikx "${{ steps.start-devproxy.outputs.proxy-url }}" \
            https://jsonplaceholder.typicode.com/posts

      - name: Stop recording
        uses: ./record-stop

      - name: Show logs
        if: always()
        run: |
          echo "Dev Proxy logs:"
          cat devproxy.log

  test-new-approach:
    name: Test New Approach (Auto-Record)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dev Proxy
        id: install-latest
        uses: ./install

      - name: Start Dev Proxy with auto-record
        id: start-devproxy
        uses: ./start
        with:
          log-file: devproxy.log
          auto-record: "true"

      - name: Send request
        run: |
          curl -ikx "${{ steps.start-devproxy.outputs.proxy-url }}" \
            https://jsonplaceholder.typicode.com/posts

      - name: Stop recording
        uses: ./record-stop

      - name: Show logs
        if: always()
        run: |
          echo "Dev Proxy logs:"
          cat devproxy.log
