name: Test Setup Specific Version

on:
  workflow_dispatch:

jobs:
  test-setup-specific-version:
    name: Test Setup Specific Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Setup Specific Version
        id: setup-version
        uses: ./setup
        with:
          version: v0.29.2
          auto-start: false

      - name: Verify Installation
        run: |
          # Check if devproxy binary exists in the expected location
          if [ -f "./devproxy/devproxy" ]; then
            echo "✅ Dev Proxy binary found"
            
            # Get the version and check if it matches the expected version
            version_output=$(./devproxy/devproxy --version 2>&1 || echo "Version check failed")
            echo "Version output: $version_output"
            
            if echo "$version_output" | grep -q "0.29.2"; then
              echo "✅ Correct version (v0.29.2) installed"
            else
              echo "❌ Expected version v0.29.2 but got: $version_output"
              exit 1
            fi
          else
            echo "❌ Dev Proxy binary not found at ./devproxy/devproxy"
            exit 1
          fi
