name: Test Start Action with Auto-Record

on:
  workflow_dispatch:

jobs:
  test-start-auto-record:
    name: Test Start Action with Auto-Record
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dev Proxy
        id: install-latest
        uses: ./install

      - name: Start Dev Proxy with auto-record
        id: start-devproxy
        uses: ./start
        with:
          log-file: devproxy.log
          auto-record: "true"

      - name: Verify Auto-Record is Active
        run: |
          echo "🔍 Verifying auto-record is active..."

          # Check if Dev Proxy is running and recording
          response=$(curl -s --max-time 10 \
            ${{ steps.start-devproxy.outputs.api-url }})
          if [ $? -eq 0 ] && [ -n "$response" ]; then
            echo "✅ Dev Proxy is running and responsive"
            echo "📋 API Response: $response"

            # Check if recording is enabled
            if echo "$response" | grep -q '"recording":true'; then
              echo "✅ Auto-record is working - Dev Proxy is recording"
            else
              echo "❌ Auto-record failed - Dev Proxy is not recording"
              exit 1
            fi
          else
            echo "❌ Dev Proxy is not responsive"
            exit 1
          fi

      - name: Test Proxy with Recording
        run: |
          echo "🔍 Testing proxy functionality with recording..."
          curl -ikx "${{ steps.start-devproxy.outputs.proxy-url }}" \
            https://jsonplaceholder.typicode.com/posts

      - name: Stop recording
        uses: ./record-stop

      - name: Show logs
        if: always()
        run: |
          echo "📋 Dev Proxy logs:"
          if [ -f "devproxy.log" ]; then
            cat devproxy.log
          else
            echo "No log file found"
          fi

  test-start-without-auto-record:
    name: Test Start Action without Auto-Record (Default)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dev Proxy
        id: install-latest
        uses: ./install

      - name: Start Dev Proxy without auto-record
        id: start-devproxy
        uses: ./start
        with:
          log-file: devproxy.log

      - name: Verify Auto-Record is NOT Active
        run: |
          echo "🔍 Verifying auto-record is NOT active..."

          # Check if Dev Proxy is running but not recording
          response=$(curl -s --max-time 10 \
            ${{ steps.start-devproxy.outputs.api-url }})
          if [ $? -eq 0 ] && [ -n "$response" ]; then
            echo "✅ Dev Proxy is running and responsive"
            echo "📋 API Response: $response"

            # Check if recording is disabled
            if echo "$response" | grep -q '"recording":false'; then
              echo "✅ Default behavior working - Dev Proxy is NOT recording"
            else
              echo "❌ Default behavior failed - " \
                "Dev Proxy should not be recording"
              exit 1
            fi
          else
            echo "❌ Dev Proxy is not responsive"
            exit 1
          fi

      - name: Test Proxy without Recording
        run: |
          echo "🔍 Testing proxy functionality without recording..."
          curl -ikx "${{ steps.start-devproxy.outputs.proxy-url }}" \
            https://jsonplaceholder.typicode.com/posts

      - name: Show logs
        if: always()
        run: |
          echo "📋 Dev Proxy logs:"
          if [ -f "devproxy.log" ]; then
            cat devproxy.log
          else
            echo "No log file found"
          fi
