name: Test Dev Proxy Actions with defaults

on:
  workflow_dispatch:

jobs:
  test-dev-proxy-actions-defaults:
    name: Test Dev Proxy Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dev Proxy
        id: setup-devproxy
        uses: ./setup
        with:
          auto-record: true

      - name: Send request
        id: send-request
        run: |
          curl -ikx "${{ steps.setup-devproxy.outputs.proxy-url }}" https://jsonplaceholder.typicode.com/posts

      - name: Show logs
        if: always()
        run: |
          echo "Dev Proxy logs:"
          cat devproxy.log
