name: Test Dev Proxy integration with Playwright

on:
  workflow_dispatch:

jobs:
  test-playwright-web-app:
    name: Dev Proxy integration with Playwright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./tests/playwright-web-app
        run: npm ci

      - name: Install Edge browser
        working-directory: ./tests/playwright-web-app
        run: npm run install:msedge

      - name: Install Dev Proxy
        uses: ./install
        with:
          version: v0.29.2

      - name: Start Dev Proxy
        uses: ./start
        with:
          config-file: "./tests/playwright-web-app/.devproxy/devproxyrc.json"
      
      - name: Install the Dev Proxy certificate for Chromium
        uses: ./chromium-cert
      
      - name: Run Playwright tests
        working-directory: ./tests/playwright-web-app
        run: npm test

      - name: Show logs
        if: always()
        run: |
          echo "Dev Proxy logs:"
          cat devproxy.log
